version: "2"

services:
  rabbitmq-node-1:
    image: rabbitmq:3.10.5-alpine
    container_name: rabbitmq-node-1
    hostname: rabbitmq-node-1
    ports:
      - "15672:15672"
    networks:
      - cluster-rabbitmq
    volumes:
      - $PWD/storage/rabbitmq-node-1:/var/lib/rabbitmq
    env_file:
      - ./.env
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}

  rabbitmq-node-2:
    image: rabbitmq:3.10.5-alpine
    container_name: rabbitmq-node-2
    hostname: rabbitmq-node-2
    ports:
      - "15673:15672"
    networks:
      - cluster-rabbitmq
    volumes:
      - $PWD/storage/rabbitmq-node-2:/var/lib/rabbitmq
    env_file:
      - ./.env
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}

  rabbitmq-node-3:
    image: rabbitmq:3.10.5-alpine
    container_name: rabbitmq-node-3
    hostname: rabbitmq-node-3
    ports:
      - "15674:15672"
    networks:
      - cluster-rabbitmq
    volumes:
      - $PWD/storage/rabbitmq-node-3:/var/lib/rabbitmq
    env_file:
      - ./.env
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}

  haproxy:
    image: haproxy-server:latest
    container_name: haproxy
    hostname: haproxy
    ports:
      - "5672:5672"
      - "1936:1936"
    networks:
      - cluster-rabbitmq

networks:
  cluster-rabbitmq:
    driver: bridge
